todoweb:
#  build: ./todo-web
  image: roundand/todo-web:v1
  ports:
    - "80:80"
  links:
   - todoserver1:todoserver1
   - todoserver2:todoserver2
   - todoserver3:todoserver3
todoserver1:
  build: ./todo-server
  ports:
    - "8000"
  links:
   - todomongodb
  env_file:
   - proxies.env
todoserver2:
  build: ./todo-server
  ports:
    - "8000"
  links:
   - todomongodb
  env_file:
   - proxies.env
todoserver3:
  build: ./todo-server
  ports:
    - "8000"
  links:
   - todomongodb
  env_file:
   - proxies.env
todomongodb:
  image: mongo
todomongoui:
  image: knickers/mongo-express
  links:
   - todomongodb:mongo
  ports: 
   - "8081:8081"
