todoweb:
  build: ./nowdoit-web
  ports:
    - "80:80"
  links:
   - todoserver1:todoserver1
   - todoserver2:todoserver2
   - todoserver3:todoserver3
todoserver1:
  build: ./nowdoit-server
  ports:
    - "8000"
  links:
   - todomongodb
todoserver2:
  build: ./nowdoit-server
  ports:
    - "8000"
  links:
   - todomongodb
todoserver3:
  build: ./nowdoit-server
  ports:
    - "8000"
  links:
   - todomongodb
todomongodb:
  image: mongo
